### PR TITLE
added gitignore with npm script

### PR DESCRIPTION
**Pull request by kharbanda14**
- added gitignore file not to track the node_modules when installed
- added npm script to start the gulp process to avoid installing the gulp cli globally and stay on the version mentioned in the package.json.

to start the server we can use the following command : 
```
npm run start
```

### CODE REVIEW

**Comment by tuliocll** [comment]
what do you think to change the default index file on `gulpfile` ?
like this:
```javascript
// Static Server
gulp.task("serve", function (done) {
  browserSync.init({
    server: {
      baseDir: Paths.TEMPLATE,
      index: "mint-main.html",
    },
  });
  done();
});

```

**Comment by kharbanda14** [comment]
@tuliocll thanks for the suggestion, i recently pushed a new commit.

**Comment by BhavikJain07** [comment]
will including node modules won't make it dependent on any backend server?

**Comment by tuliocll** [comment]
> will including node modules won't make it dependent on any backend server?

no, we just have gulp, sass and browser-sync dependencies for development just to running the local server, on production we all ready have the static files (html, js, css...).

**Pull request merged**
