### PR TITLE
New logo (logo + font + colour)

### PR DESCRIPTION
**Pull request by SebastJava**
linuxmint-logo-name-oxa-green

image

I was afraid of being too late, so i did this PR before creating the web page to promote this...
* **New logo:** stronger, with an infinite L coming from above (other versions also included).
* **New font:** Oxanium. Half square, half round, this font works well with the logo.
* **New colour:** In order to promote this subtle logo change, i had to change the colour too.

(This old grayish khaki, this #86BE43, had to be replaced. It just doesn't work. This hue is a yellow-green, so it must be heavily subdued, and then it just doesn't look good. Moreover, if you do a quick web search for "mint green", you will find it is more like this new colour here. This new colour is just much better. Anyway, these are all SVG files, so this new colour could be reverted easily on all files, with just one `sed` command: `sed -i 's/#00b894/#86be43/g' *.svg` But please don't do that. This #00B894 is much better for the LinuxMint logo AND it also fits much better with our new website colours. This new colour was found on https://flatuicolors.com/palette/us and it's called... MintLeaf.)

I am still working on a web page to promote (and explain) all this. Coming soon.

### CODE REVIEW

**Comment by SebastJava** [comment]
mint-wizixo-prv-1
mint-wizixo-prv-2

**Comment by Secret-chest** [comment]
1. The font really sucks.
2. We aren't supposed to use camel case.
3. Why change the logo?

**Comment by SebastJava** [comment]
Frankly, I'm a little depressed right now. I lost a lot of my summer time working on a lot of little things for LinuxMint. I do not have air conditioning and it is not comfortable here now. I don't know if I will continue or not. Maybe I'll stop bothering you. Leave you with this logo that is "not too strong", and this greyish khaki colour.

**Comment by Secret-chest** [comment]
> Frankly, I'm a little depressed right now. I lost a lot of my summer time working on a lot of little things for LinuxMint. I do not have air conditioning and it is not comfortable here now. I don't know if I will continue or not. Maybe I'll stop bothering you. Leave you with this logo that is "not too strong", and this greyish khaki colour.

@SebastJava Really sorry. I didn't want to make you feel bad.
Also I like the color and the infinite L, but not the font and capitalization. If you could change it to Ubuntu or Poppins then it would be great.

**Comment by clefebvre** [comment]
I'll close this for now. The logo work moved to brand-logo. We'll need to work on fonts to make logo+names in that project as well and then we'll use them here.

**Pull request closed without merging**
