### PR TITLE
About:  some ui color tweakings to make cards pop

### PR DESCRIPTION
**Pull request by imsamimalik**
image

### CODE REVIEW

**Comment by clefebvre** [comment]
I like it at first sight. But I find it distracting when reading the page. It emphasize too many items imo.

**Comment by imsamimalik** [comment]
Okay. Then we can remove the border but can keep the bg color for dots. Is that alright?

**Comment by imsamimalik** [comment]
because the everything was so dull.

**Comment by imsamimalik** [comment]
@clefebvre I'm resetting the changes of about page. and making a new PR

**Pull request closed without merging**
