### PR TITLE
New logo2 + all fonts converted to path

### LINKED ISSUE #12: template/img/logo.svg and logo-mono.svg are made of Ubuntu font... Convert to path to ensure compatibility
The names for these logos are made of text, with the Ubuntu font. Nice, but this will only work on Linux computers ! Am i right ?

I think these "linuxmint" texts should be converted to path, to get a constant look on all computers. But this origin text could still be kept on a separate, hidden layer, in case you want to edit it later. I am working on this now. I will make a pull request soon:

* wizixo/template/img/favicon.ico (new and corrected version)
* wizixo/template/img/logo.svg (current version, text converted to path)
* wizixo/template/img/logo-mono.svg (current version, text converted to path)
* wizixo/template/img/logo2-name.svg (new version, text converted to path)
* wizixo/template/img/logo2-name-green.svg (new version, text converted to path)
* wizixo/template/img/logo2-name-mono.svg (new version, text converted to path)

logo2-name-green

### PR DESCRIPTION
**Pull request by SebastJava**
preview-dir

Close #12 
* All Ubuntu fonts converted to path to ensure compatibility on all platforms without having to care about exporting fonts.
* New logo2 added as a second, possible choice. See preview here:

preview-logo2

### CODE REVIEW

**Comment by SebastJava** [comment]
**Words about colour:**
I forgot to mention this #4CBD89 colour on logo2. Okay, i admit it: I keep hesitating over colours. That one comes from the current top nav bar appearing when you scroll down... Just another suggestion here. But i think that if you go with a theme that comes with a different colour, then the logo colour should be changed accordingly. So, i just "colorpicked" this from your Wizixo theme. MintLeaf, #00B894, is another great possibility.

**Comment by whelmich** [comment]
I think the text to path conversion is a good solution for the logo!

One thing that could be improved: The files in this PR are stored as Inkscape SVG format, which contains editor specific data. For web you could use the Optimized SVG file format in Inkscape > Save, to remove metadata, comments and disable pretty-printing (see options dialog). 

For e.g. logo-mono.svg this would reduce the file size from 11.2kB to 5.9kB.

**Comment by SebastJava** [comment]
@whelmich Yes ! Thanks for the advice. I saw this increase in file size and was not totally comfortable with it. This is better. I just did a quick test, with all the default settings: 11.2 kB -> 6.4 kB. The origin logo, made of Ubuntu font, weighted 6.8 kB. So, converting to path and saving as Optimized SVG makes this logo both universal AND lightweight.

But right now i am facing broader perspectives. There is a separate discussion going on about a possible new version. Some re-design. And maybe some colour change. I don't know what i will do. I think there will be a separate, new repository on GitHub: **linuxmint/logo**.

So, we will probably work on the logo somewhere else, and not care about file size at this time. But i should have this **converting to path and saving as Optimized SVG** written in the README.md on the linuxmint/logo on GitHub. Just to ensure i don't forget to do these converts on the final steps... And then, finally update this PR here... Right now, this PR is "frozen".

**Comment by SebastJava** [comment]
> But right now i am facing broader perspectives. There is a separate discussion going on about a possible new version. Some re-design. And maybe some colour change. I don't know what i will do. I think there will be a separate, new repository on GitHub: **linuxmint/logo**.

WIP: https://github.com/SebastJava/linuxmint-logo/tree/official (just re-started...)

**Comment by SebastJava** [comment]
website-PR2

* New design.
* Complete re-edition.
* Carefully crafted with just a bit of manual kerning.
* Fonts converted to path, source font layer deleted, and saved as Optimized SVG.

For re-edits, source files (with fonts on a separate hidden layer) can be found there:
https://github.com/SebastJava/linuxmint-logo/tree/official/website-PR-SOURCES

**Comment by SebastJava** [comment]
New PR coming up soon to replace this one...

**Pull request closed without merging**
